{"date": "May 21 2017 00:44:43" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:38:14" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:42:36" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:45:44" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:46:18" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:48:19" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:54:00" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:54:36" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:55:25" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:57:11" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:58:09" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 01:58:42" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:00:30" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:01:23" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:02:30" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:05:30" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:05:59" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:07:30" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "May 21 2017 02:11:40" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 14:53:29" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 14:54:04" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 14:54:41" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 14:55:05" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:08:04" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:09:10" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:15:53" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:16:34" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:20:57" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:21:19" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:21:47" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:24:16" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:24:46" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:25:05" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:28:05" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:34:29" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:44:14" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:48:46" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Jun 28 2017 15:56:54" , "result": "OK" , "log":{'status': 'OK', 'ansible_task': TASK: debug loops, 'ansible_host': u'192.168.100.1', 'ansible_result': u'{"changed": false, "msg": "All items completed"}', 'ansible_type': 'task'}  }

{"date": "Aug 12 2017 06:12:33" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 06:13:34" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 06:15:00" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 06:15:35" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 06:16:42" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 06:20:57" , "result": "UNREACHABLE" , "log":{'msg': u'timed out', 'unreachable': True, 'changed': False}  }

{"date": "Aug 12 2017 11:28:09" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:30:09" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:31:56" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:32:29" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:32:46" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:34:57" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:35:53" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:37:45" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:38:01" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'stdout': ''}  }

{"date": "Aug 12 2017 11:38:27" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:38:40" , "result": "OK" , "log":{'status': 'OK', 'ansible_task': TASK: f, 'ansible_host': u'192.168.100.1', 'ansible_result': u'{\n    "changed": false, \n    "msg": "seq|to_bool"\n}', 'ansible_type': 'task'}  }

{"date": "Aug 12 2017 11:38:40" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:39:21" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:40:09" , "result": "OK" , "log":{'status': 'OK', 'ansible_task': TASK: f, 'ansible_host': u'192.168.100.1', 'ansible_result': u'{\n    "changed": false, \n    "msg": "seq|to_bool"\n}', 'ansible_type': 'task'}  }

{"date": "Aug 12 2017 11:40:09" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:40:49" , "result": "OK" , "log":{'status': 'OK', 'ansible_task': TASK: f, 'ansible_host': u'192.168.100.1', 'ansible_result': u'{\n    "changed": false, \n    "msg": "seq|to_bool"\n}', 'ansible_type': 'task'}  }

{"date": "Aug 12 2017 11:40:49" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 11:41:22" , "result": "OK" , "log":{'status': 'OK', 'ansible_task': TASK: f, 'ansible_host': u'192.168.100.1', 'ansible_result': u'{\n    "changed": false, \n    "msg": "seq|int"\n}', 'ansible_type': 'task'}  }

{"date": "Aug 12 2017 11:41:22" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 97, in run\n    item_results = self._run_loop(items)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 290, in _run_loop\n    res = self._execute(variables=task_vars)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:23:13" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:23:31" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:33:19" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:33:26" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:34:22" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:44:11" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:44:43" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:46:54" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:47:08" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

{"date": "Aug 12 2017 12:47:21" , "result": "FAILED" , "log":{'msg': 'Unexpected failure during module execution.', 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 125, in run\n    res = self._execute()\n  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 462, in _execute\n    self._task.post_validate(templar=templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/task.py", line 247, in post_validate\n    super(Task, self).post_validate(templar)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate\n    value = templar.template(getattr(self, name))\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 431, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 386, in template\n    disable_lookups=disable_lookups,\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 556, in do_template\n    myenv.filters.update(self._get_filters())\n  File "/usr/local/lib/python2.7/dist-packages/ansible/template/__init__.py", line 240, in _get_filters\n    plugins = [x for x in self._filter_loader.all()]\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all\n    self._module_cache[path] = self._load_module_source(name, path)\n  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source\n    module = imp.load_source(name, path, module_file)\n  File "/home/ansible/plugins/filter/core.py", line 52, in <module>\n    from ansible.module_utils.six.moves import reduce, shlex_quote\nImportError: cannot import name shlex_quote\n', 'stdout': ''}  }

